version: '3.8'

services:
  rust:
    env_file: ./.env
    build: ./.docker
    container_name: 'ddd_bottom_up_tutorial'
    volumes:
      - type: bind
        source: .
        target: /var/www
    depends_on:
      - db
    environment:
      CARGO_BUILD_TARGET_DIR: /tmp/target
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    ports:
      - "8082:8080"
    networks:
      - app-network
    tty: true
  db:
    env_file: ./.env
    image: postgres:latest
    container_name: 'ddd_bottom_up_tutorial_db'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
