[package]
name = "ddd_sample"
version = "0.1.0"
publish = false
edition = "2021"

[dependencies]
anyhow = { workspace = true }
uuid = { workspace = true }
rstest = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
